name: Deploy to Amazon EC2
on:
  push:
    branches: [ "dev" ]
    paths-ignore:
      - "docs/**"
      - "**/*.md"
env:
  APP_NAME: search-service
  REGISTRY: ghcr.io
  IMAGE_NAME: today-book/search-service-dev
  VERSION: latest
  PROFILE: dev

jobs:
  deploy:
    environment: dev
    name: Build Docker Image and Deploy EC2
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK # JDK 지정
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Build with Gradle
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x gradlew
          ./gradlew build -x test

      - name: Log into container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          docker build -t $IMAGE .
          docker push $IMAGE
          echo "IMAGE_URI=$IMAGE" >> $GITHUB_ENV

      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DEV_REMOTE_IP }}
          username: ${{ secrets.DEV_REMOTE_USER }}
          key: ${{ secrets.DEV_REMOTE_PRIVATE_KEY }}
          port: ${{ secrets.DEV_REMOTE_SSH_PORT }}
          script: |
            echo "--- 배포 시작 ---"
            sudo docker stop ${{ env.APP_NAME }} || true
            sudo docker rm ${{ env.APP_NAME }} || true
            sudo docker rmi ${{ env.IMAGE_URI }} || true
            
            echo "GHCR 로그인"
            echo ${{ secrets.GITHUB_TOKEN }} | sudo docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            echo "이미지 Pull"
            sudo docker pull ${{ env.IMAGE_URI }}
            
            sudo docker run -d --name ${{ env.APP_NAME }} -p 9005:9005 \
            -v /home/ubuntu/app/certs/opensearch.crt:/app/certs/opensearch.crt \
            -v /etc/gcp/keys/search-key.json:/var/secrets/gcp/search-key.json \
            -e GOOGLE_APPLICATION_CREDENTIALS=/var/secrets/gcp/search-key.json \
            -e SPRING_PROFILES_ACTIVE=${{ env.PROFILE }} \
            -e OPENSEARCH_CERT_PATH=file:/app/certs/opensearch.crt \
            -e OPENSEARCH_URIS=${{ secrets.DEV_OPENSEARCH_URIS }} \
            -e OPENSEARCH_USERNAME=${{ secrets.DEV_OPENSEARCH_USERNAME }} \
            -e OPENSEARCH_PASSWORD=${{ secrets.DEV_OPENSEARCH_PASSWORD }} \
            -e GCP_PROJECT_ID=${{ secrets.VERTEX_AI_PROJECT_ID }} \
            --network internal-net \
            ${{ env.IMAGE_URI }}
            
            echo "--- 배포 완료 ---"